services:

  chatexu-db:
    image: mongo:latest
    container_name: chatexu-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: "chatexu"
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  chatexu-server:
    container_name: chatexu-server
    image: chatexu-server:0.3.0
    ports:
      - '8091:8091'
    volumes:
      - icons:/server/src/main/resources/icons/
      - images:/server/src/main/resources/chats/
    networks:
      - app-network
    depends_on:
      - chatexu-db

volumes:
  mongo:
  icons:
  images:

networks:
 app-network:
   driver: bridge