version: '3'
services:

  chatexu-db:
    container_name: chatexu-db
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo:/var/lib
    networks:
      - app-network
  
  chatexu-server:
    container_name: chatexu-server
    image: chatexu-server:0.1.0
    ports:
      - '8091:8091'
    networks:
      - app-network
    depends_on:
      - chatexu-db

volumes:
  mongo:

networks:
 app-network:
   driver: bridge